"""initial_schema

Revision ID: 3f0c9199ae76
Revises: 
Create Date: 2026-08-18 22:32:28.367908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '3f0c9199ae76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('geofences',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('owner_id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('CIRCLE', 'POLYGON', name='geofencetype'), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geofences_owner_id', 'geofences', ['owner_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('user_id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('CAR', 'TRUCK', 'MOTORCYCLE', 'VAN', name='vehicletype'), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IDLE', 'OFFLINE', 'MAINTENANCE', name='vehiclestatus'), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_device_id'), 'vehicles', ['device_id'], unique=True)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_index('ix_vehicles_user_id', 'vehicles', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('vehicle_id', app.models.types.GUID(), nullable=False),
    sa.Column('geofence_id', app.models.types.GUID(), nullable=True),
    sa.Column('type', sa.Enum('GEOFENCE_ENTER', 'GEOFENCE_EXIT', 'SPEEDING', 'OFFLINE', 'LOW_BATTERY', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_index('ix_alerts_vehicle_id', 'alerts', ['vehicle_id'], unique=False)
    op.create_table('geofence_vehicles',
    sa.Column('geofence_id', app.models.types.GUID(), nullable=False),
    sa.Column('vehicle_id', app.models.types.GUID(), nullable=False),
    sa.Column('alert_on_enter', sa.Boolean(), nullable=True),
    sa.Column('alert_on_exit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('geofence_id', 'vehicle_id')
    )
    op.create_index('ix_geofence_vehicles_geofence_id', 'geofence_vehicles', ['geofence_id'], unique=False)
    op.create_index('ix_geofence_vehicles_vehicle_id', 'geofence_vehicles', ['vehicle_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('vehicle_id', app.models.types.GUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_timestamp'), 'locations', ['timestamp'], unique=False)
    op.create_index('ix_locations_vehicle_id', 'locations', ['vehicle_id'], unique=False)
    op.create_index('ix_locations_vehicle_timestamp', 'locations', ['vehicle_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locations_vehicle_timestamp', table_name='locations')
    op.drop_index('ix_locations_vehicle_id', table_name='locations')
    op.drop_index(op.f('ix_locations_timestamp'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_geofence_vehicles_vehicle_id', table_name='geofence_vehicles')
    op.drop_index('ix_geofence_vehicles_geofence_id', table_name='geofence_vehicles')
    op.drop_table('geofence_vehicles')
    op.drop_index('ix_alerts_vehicle_id', table_name='alerts')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_vehicles_user_id', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_device_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_geofences_owner_id', table_name='geofences')
    op.drop_table('geofences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
